### ISSUE TITLE
Falta una letra

### ISSUE THREAD

**Issue by iblancasa** [oslugr/XVIcampa-a#3]
Cuando se habla de Firefox, pone "operatvo" en vez de "operativo".
No puedo modificarlo. Creo que es por que Git está tratándolo como un fichero binario y no ve el cambio o yo qué se

**Comment by oslugr** [comment]
Muchas gracias, soy Manu y me gusta como ha quedado en Markdown.

**Comment by oslugr** [comment]
Mañana le haré un pull a mi fork ;-)

**Comment by iblancasa** [comment]
:+1:
